### ISSUE TITLE
Is it possible to include multiple files and then compile and link them ?

### ISSUE THREAD

**Issue by AvanteElectro** [andreinechaev/nvcc4jupyter#10]
Is it possible to include multiple files and then compile and link them ?

Or do we have to put all the code after %%cu in the cell of the notebook ?

**Comment by andreinechaev** [comment]
hello @AvanteElectro 
yes, you can compile multiple files with v2 of the extension. Please review the readme. 
For each file you'll need something like 
`%%cuda --name example.cu --compile false`

**Comment by cosminc98** [comment]
The new version of the package does this using the concept of groups. Read more about them [here](https://nvcc4jupyter.readthedocs.io/en/latest/usage.html#groups).
