### ISSUE TITLE
%%cuda -n <name> does not work 

### ISSUE THREAD

**Issue by yaridor** [andreinechaev/nvcc4jupyter#11]
Hello,

Your examples in https://www.geeksforgeeks.org/how-to-run-cuda-c-c-on-jupyter-notebook-in-google-colaboratory/ works OK.
Then I tried: 

%%cuda -n drive/MyDrive/cuda1.cu  (cuda1.cu includes the code of your of "maximum element from vector ".  I mounted my good drive which includes cuda1.cu.  But I get 
UsageError: %%cuda is a cell magic, but the cell body is empty.

what am I doing wrong ?

Thanks in advance,

**Comment by yaridor** [comment]
Hello,

>  If I understand correctly, you want to load an external file from your Google Drive. It is an interesting use case, I can look into it.

Yes. This is exactly what I want to do.  thanks for considering this option

> To resolve your issue I'd recommend to either copy your code into the cell. Or as another option copy your cuda source file into the home directory and then run a cell with
> %%cuda_run

I am still not sure how to use "cuda_run" with my Cuda file in my home directory. do you have an example of using cuda_run ?

**Comment by andreinechaev** [comment]
`cuda_run` will take all cuda files in your home dir and will compile and run them.
use it as in the initial comment. Just will an empty cell with exactly this
```
%%cuda_run
# This line just to bypass an exeption and can contain any text
```
