### ISSUE TITLE
Error while using in Colab

### ISSUE THREAD

**Issue by dog-ai-project** [andreinechaev/nvcc4jupyter#14]
**!pip install git+git://github.com/andreinechaev/nvcc4jupyter.git**

Error 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+git://github.com/andreinechaev/nvcc4jupyter.git
  Cloning git://github.com/andreinechaev/nvcc4jupyter.git to /tmp/pip-req-build-uc38iq2f
  Running command git clone -q git://github.com/andreinechaev/nvcc4jupyter.git /tmp/pip-req-build-uc38iq2f
  fatal: unable to connect to github.com:
  github.com[0: 140.82.114.4]: errno=Connection timed out

WARNING: Discarding git+git://github.com/andreinechaev/nvcc4jupyter.git. Command errored out with exit status 128: git clone -q git://github.com/andreinechaev/nvcc4jupyter.git /tmp/pip-req-build-uc38iq2f Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q git://github.com/andreinechaev/nvcc4jupyter.git /tmp/pip-req-build-uc38iq2f Check the logs for full command output.

**Comment by udonne** [comment]
Try

`!pip install git+https://github.com/andreinechaev/nvcc4jupyter.git`

(https instead of git)

**Comment by rohitashwani1** [comment]
It is also giving an error.
I am unable to load the nvcc plugin

**Comment by cosminc98** [comment]
@rohitashwani1 A major update was just introduced. Please follow [these instructions](https://nvcc4jupyter.readthedocs.io/en/latest/usage.html).
