### ISSUE TITLE
Problem on %load_ext nvcc_plugin, when running CUDA

### ISSUE THREAD

**Issue by amanmishra1321** [andreinechaev/nvcc4jupyter#16]
I followed this tutorial to run CUDA code on COLAB:

https://medium.com/@iphoenix179/running-cuda-c-c-in-jupyter-or-how-to-run-nvcc-in-google-colab-663d33f53772

but when I give this command:

%load_ext nvcc_plugin

I get this error:
Cloning git://github.com/andreinechaev/nvcc4jupyter.git to /tmp/pip-req-build-qlz3kouf
ERROR: Command errored out with exit status 128: git clone -q git://github.com/andreinechaev/nvcc4jupyter.git /tmp/pip-req-build-qlz3kouf Check the logs for full command output.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-39-79d7ff0447b0>](https://localhost:8080/#) in <cell line: 2>()
      1 get_ipython().system('pip install git+git://github.com/andreinechaev/nvcc4jupyter.git')
----> 2 get_ipython().run_line_magic('load_ext', 'nvcc_plugin')

7 frames
<decorator-gen-57> in load_ext(self, module_str)

/usr/lib/python3.9/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'nvcc_plugin'

**Comment by tojiboyevf** [comment]
I guess the problem with `pip install git+git://github.com/andreinechaev/nvcc4jupyter.git`. Try `pip install git+https://github.com/andreinechaev/nvcc4jupyter.git`.
