### ISSUE TITLE
Is it possible to specify C++ standard version for compilation? C++17, C++20?

### ISSUE THREAD

**Issue by Alvov1** [andreinechaev/nvcc4jupyter#19]
Wanna use C++20 features inside Cuda code

**Comment by cosminc98** [comment]
Added a feature that allows you to pass arguments to the compiler (nvcc). The cell magic would look something like:
```
%%cuda --compiler-args "--std c++20"
```

Be aware that you need at least version 12 of "nvcc" to be able to compile with C++ 20. See [this page](https://gist.github.com/ax3l/9489132#device-side-c-standard-support) for more details.
