### ISSUE TITLE
ModuleNotFoundError: No module named 'nvcc_plugin'

### ISSUE THREAD

**Issue by ekagra-ranjan** [andreinechaev/nvcc4jupyter#25]
Hi!

I am running the he following to load enable colab to run cuda:

```
!nvcc --version
!pip install git+https://github.com/andreinechaev/nvcc4jupyter.git
%load_ext nvcc_plugin
```

It was working fine till yesterday and today I come across this issue. I see [someone else also facing this issue today](https://github.com/andreinechaev/nvcc4jupyter/issues/14#issuecomment-1906690740).

Error
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-5df49c27db81>](https://localhost:8080/#) in <cell line: 1>()
----> 1 get_ipython().run_line_magic('load_ext', 'nvcc_plugin')

7 frames
<decorator-gen-57> in load_ext(self, module_str)

/usr/lib/python3.10/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'nvcc_plugin'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

Has something changed? Thank you!

**Comment by Barenya255** [comment]
%load_ext nvcc_plugin
This should be %load_ext nvcc4jupyter, as is in the Readme.

**Comment by cosminc98** [comment]
Just like @Barenya255 said, the API was updated recently. This particular change was made to not have to remember the "nvcc_plugin" name as well as the name of the package "nvcc4jupyter" (now you only need to know the package name). Also, you can install from pypi directly by running: 
```
pip install nvcc4jupyter
```

**Comment by ekagra-ranjan** [comment]
Thank you for the help!
