### ISSUE TITLE
new line is not detected 

### ISSUE THREAD

**Issue by shahidul56** [andreinechaev/nvcc4jupyter#3]
![edw](https://user-images.githubusercontent.com/11449967/56632045-c6915500-6679-11e9-9638-345fa55dd289.PNG)
 \n is not recognized by nvcc4jupyter

it will be better if it give output not in a one line but in sptep wise output

**Comment by andreinechaev** [comment]
Thanks for creating the issue. A PR would be welcome. I will take a look myself anytime soon.

**Comment by andreinechaev** [comment]
fixed. closing the issue
