### ISSUE TITLE
Include addtional cu/c++ files in jupyter

### ISSUE THREAD

**Issue by yiakwy** [andreinechaev/nvcc4jupyter#6]
When I use jupyter I will develop a normal python package and use notebook as an interface to do some experiments upon the released package.

I wonder if I can include addtional  customer cu/c++ files in a cell. For example, we could write gtests in jupyter to do experiments upon the cu package and share the result to peers.

Is there any way to do that?

**Comment by andreinechaev** [comment]
do you mean in the same cell? If so, then you need to modify your sources. 
The second version  of the plugin supports named cells. Where each cell will be save into a source file.
```Mark a cell to be treated as cuda cell
%%cuda --name example.cu --compile false```

please review the readme

**Comment by andreinechaev** [comment]
@yiakwy ?

**Comment by andreinechaev** [comment]
Seems no more interest here.
