### ISSUE TITLE
nvprof

### ISSUE THREAD

**Issue by rakati** [andreinechaev/nvcc4jupyter#8]
does this extension support nvprof? if not I will be very interested in working with you to implement this feature.

**Comment by andreinechaev** [comment]
Have you looked into the command line capabilities of NVprof? AFAIK it's a UI utility. Quite powerful, but still. 
Frankly, I thought about looking into it but didn't have chance yet. 
We cannot visualize the utility itself. Although, if it can write some metrics into the discs even pythonic tools can be used (ie matplotlib)
The first step would be to understand what NVprof is capable of as a vanilla bash utility.
