### ISSUE TITLE
Error while trying to use %%cuda_run and %%cuda magic

### ISSUE THREAD

**Issue by KarthikRIyer** [andreinechaev/nvcc4jupyter#9]
![image](https://user-images.githubusercontent.com/35020024/101595414-53d51900-3a19-11eb-83d0-935ebca55c30.png)

I'm also getting this error while trying to specify the `-c` flag with %%cuda

**Comment by andreinechaev** [comment]
Hi @KarthikRIyer it looks like you're trying to compile some python code. When the extension is made for acids C/C++.
